// Answer matching, kept separate from quiz.js (and free of DOM access) so
// it can run identically in the browser and under plain Node for the
// self-test in scripts/self-test.js.

// Lowercase + fold apostrophe look-alikes to one canonical character +
// collapse whitespace. This is intentionally NOT fuzzy -- every step is a
// deterministic character substitution, not an edit-distance tolerance.
// The apostrophe fold specifically exists because mobile keyboards render a
// typed apostrophe as any of several Unicode lookalikes (straight, curly
// open/close, modifier letter); without folding them to one character here,
// typing a curly apostrophe would fail to exact-match a generated accepted
// answer that (per generateAcceptedAnswers below) always uses the straight
// one, since data.js's source strings only ever use "'". Do not add
// anything here that forgives a genuinely different character (like the old
// oo<->u/aa<->a folding did) -- those are now explicit accepted-answer
// variants instead, generated per item, so one item's tolerance can never
// leak into accepting a different, wrong verb (see generateAcceptedAnswers).
function normalizeAnswer(str) {
  return str
    .toLowerCase()
    .replace(/['’‘ʼ]/g, "'")
    .trim()
    .replace(/\s+/g, " ");
}

// Only the transforms that actually apply to a given word are combined, so
// a word with none of apostrophe/oo/aa produces exactly one variant
// (itself); a word where exactly one transform applies produces two; a word
// where multiple transforms apply produces the real combination of all of
// them (e.g. an apostrophe AND "oo" together produce four).
function applicableTransforms(str) {
  const transforms = [];
  if (str.includes("'")) transforms.push((s) => s.replace(/'/g, ""));
  if (str.includes("oo")) transforms.push((s) => s.replace(/oo/g, "u"));
  if (str.includes("aa")) transforms.push((s) => s.replace(/aa/g, "a"));
  return transforms;
}

// Precomputes every known-safe spelling variant of a canonical answer as
// explicit, exact strings. This replaces the old Levenshtein-1 typo
// tolerance: fuzzy edit-distance can't distinguish "a real typo of the
// right word" from "a coincidentally similar wrong word" -- e.g. "yafam"
// (a fragment of yafham/verstoen, "to understand") is exactly one
// substitution away from ya'lam/wëssen's normalized "yalam" and was wrongly
// accepted for it. Because each item's accepted list is generated only
// from that item's own answer, this also structurally prevents any
// cross-item bleed (the earlier huwa/hiya and ana/anta bugs) -- there is no
// shared tolerance window for a different item's spelling to fall into.
function generateAcceptedAnswers(canonical) {
  const base = normalizeAnswer(canonical);
  let variants = new Set([base]);
  for (const transform of applicableTransforms(base)) {
    const next = new Set(variants);
    variants.forEach((v) => next.add(transform(v)));
    variants = next;
  }
  return Array.from(variants);
}

// Exact match only, after normalization -- no typo tolerance. Kept as a
// simple string-pair primitive (used directly by scripts/self-test.js's
// identity check); item grading goes through isCorrectForItem below, which
// checks the item's precomputed accepted-answer lists instead of a single
// "correct" string.
function isAnswerCorrect(input, correct) {
  return normalizeAnswer(input) === normalizeAnswer(correct);
}

// Grades against an item's precomputed acceptedAnswers (verb-only for
// conjugated forms, since the Lëtzebuergesch prompt already establishes the
// subject), falling back to acceptedAltAnswers (the full pronoun+verb
// phrase) if the item has one. Both lists are generated by
// generateAcceptedAnswers from that item's own answer/altAnswer only, so
// there is no fuzzy tolerance anywhere in this path -- see data.js's
// buildItems() for where the lists are built.
function isCorrectForItem(input, item) {
  const normInput = normalizeAnswer(input);
  if (item.acceptedAnswers.includes(normInput)) return true;
  if (item.acceptedAltAnswers && item.acceptedAltAnswers.includes(normInput)) return true;
  return false;
}

// ---------------------------------------------------------------------
// Character-level diff, for display only. None of the above grading
// functions are used or modified by this section -- correctness is
// already decided by isAnswerCorrect/isCorrectForItem before any of this
// runs; it only visualizes *where* an already-incorrect answer diverged.
// ---------------------------------------------------------------------

// Like normalizeAnswer, but also returns, for every character in the
// normalized output, the [start, end) slice of the *original* string that
// produced it. This lets a diff computed on normalized strings (so
// accepted spelling variants like oo/u or aa/a line up as matches, same as
// grading treats them) be rendered back against the real, un-normalized
// spelling -- apostrophes and all. Mirrors normalizeAnswer's
// transformations and their order exactly; keep the two in sync if
// normalizeAnswer ever changes.
function normalizeWithTrace(str) {
  const lower = str.toLowerCase();

  // Fold apostrophe look-alikes to one canonical character for alignment
  // purposes (mirrors normalizeAnswer) -- kept as its own span rather than
  // stripped/merged, since normalizeAnswer no longer removes apostrophes,
  // only canonicalizes which literal character represents one.
  const stage1 = [];
  for (let i = 0; i < lower.length; i++) {
    const ch = lower[i];
    const normCh = /['’‘ʼ]/.test(ch) ? "'" : ch;
    stage1.push({ ch: normCh, start: i, end: i + 1 });
  }

  // Collapse whitespace runs to a single space, trim leading/trailing.
  const stage2 = [];
  for (const entry of stage1) {
    if (/\s/.test(entry.ch)) {
      if (stage2.length === 0) continue;
      const prev = stage2[stage2.length - 1];
      if (prev.ch === " ") {
        prev.end = entry.end;
        continue;
      }
      stage2.push({ ch: " ", start: entry.start, end: entry.end });
    } else {
      stage2.push({ ch: entry.ch, start: entry.start, end: entry.end });
    }
  }
  while (stage2.length && stage2[stage2.length - 1].ch === " ") stage2.pop();

  // No oo->u/aa->a folding here anymore -- normalizeAnswer no longer does
  // it either (those are now explicit per-item accepted-answer variants,
  // not a universal fold), so mirroring it stops at whitespace collapsing.

  return {
    normalized: stage2.map((e) => e.ch).join(""),
    spans: stage2.map((e) => [e.start, e.end]),
  };
}

// Standard Levenshtein alignment with backtrace, turning string `a` into
// string `b`. Returns an ordered list of steps:
//   { op: "match" | "sub", aIndex, bIndex }
//   { op: "del", aIndex }  -- a[aIndex] has no counterpart in b
//   { op: "ins", bIndex }  -- b[bIndex] has no counterpart in a
function levenshteinAlign(a, b) {
  const m = a.length;
  const n = b.length;
  const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));
  for (let i = 0; i <= m; i++) dp[i][0] = i;
  for (let j = 0; j <= n; j++) dp[0][j] = j;
  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      dp[i][j] =
        a[i - 1] === b[j - 1]
          ? dp[i - 1][j - 1]
          : 1 + Math.min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]);
    }
  }

  // Backtrace order: match, then del/ins, then sub as the last resort.
  // When a substitution and a deletion/insertion cost exactly the same
  // (a tie in dp[i][j]), del/ins is checked first and wins -- e.g. a
  // dropped trailing letter reads as "missing" rather than as an
  // unrelated-looking mid-word "substitution", which is the more
  // intuitive framing for a human reading the diff. Only falls through to
  // "sub" when neither match nor del/ins can account for dp[i][j].
  const ops = [];
  let i = m;
  let j = n;
  while (i > 0 || j > 0) {
    if (i > 0 && j > 0 && a[i - 1] === b[j - 1] && dp[i][j] === dp[i - 1][j - 1]) {
      ops.push({ op: "match", aIndex: i - 1, bIndex: j - 1 });
      i--;
      j--;
    } else if (i > 0 && dp[i][j] === dp[i - 1][j] + 1) {
      ops.push({ op: "del", aIndex: i - 1 });
      i--;
    } else if (j > 0 && dp[i][j] === dp[i][j - 1] + 1) {
      ops.push({ op: "ins", bIndex: j - 1 });
      j--;
    } else {
      ops.push({ op: "sub", aIndex: i - 1, bIndex: j - 1 });
      i--;
      j--;
    }
  }
  ops.reverse();
  return ops;
}

// How much of the closest accepted variant's length the edit distance has
// to be before a character-by-character diff stops being useful feedback.
// Above this ratio, the typed answer isn't a near-miss typo of the right
// word anymore -- it's effectively a different word (e.g. typing "tara"
// for "tandhur" is 5 of 7 characters off) -- and forcing a Levenshtein
// alignment between two mostly-unrelated strings produces an awkward,
// confusing diff rather than useful feedback. Deliberately simple: exactly
// half, not tuned per-word or per-level.
const DIFFERENT_WORD_RATIO = 0.5;

// Chooses which of an item's accepted-answer variants -- verb-only
// (acceptedAnswers) AND full-phrase (acceptedAltAnswers, if the item has
// one), including their own spelling variants -- is closest (lowest edit
// distance) to what the user actually typed, so the diff below renders
// against whichever form they were actually attempting. Without this, the
// diff always compared against the verb-only canonical answer even when
// someone legitimately typed the full pronoun+verb phrase, so a correct
// pronoun with a wrong verb (e.g. "anta xyz" for gesinn.du, answer "tara",
// altAnswer "anta tara") would show the pronoun itself as garbled/wrong --
// aligning "anta xyz" against "tara" has no room for "anta" to be a clean
// match. Picking "anta tara" as the target instead lets the pronoun align
// as a match and only the verb show as the real mistake.
//
// Returns { answer, isDifferentWord }: `answer` is the chosen candidate
// string (already normalized, e.g. no apostrophe if that variant was
// closest); `isDifferentWord` tells the caller whether even the best
// candidate is a poor enough match that a granular diff isn't worthwhile
// (see DIFFERENT_WORD_RATIO above).
//
// Display-only, like the rest of this section: grading (isCorrectForItem)
// has already decided the answer is wrong by the time this runs, and
// nothing computed here feeds back into that decision.
function closestAcceptedAnswer(rawInput, item) {
  const candidates = item.acceptedAltAnswers
    ? item.acceptedAnswers.concat(item.acceptedAltAnswers)
    : item.acceptedAnswers;
  const normInput = normalizeAnswer(rawInput);

  let best = candidates[0];
  let bestDistance = Infinity;
  for (const candidate of candidates) {
    // Every non-"match" step in the alignment is one unit of edit
    // distance (insertion/deletion/substitution all cost 1 in
    // levenshteinAlign's DP) -- reuses the same alignment machinery as
    // diffAnswer below instead of a second distance implementation.
    const distance = levenshteinAlign(normInput, candidate).filter((op) => op.op !== "match").length;
    if (distance < bestDistance) {
      bestDistance = distance;
      best = candidate;
    }
  }
  return {
    answer: best,
    isDifferentWord: bestDistance > best.length * DIFFERENT_WORD_RATIO,
  };
}

// Computes a display-ready diff between what the user typed (`rawInput`)
// and the correct answer (`correctAnswer`), for visualizing where an
// already-incorrect answer diverged. Alignment runs on normalized forms
// (so tolerated spelling variants show as matches, not false mismatches);
// rendering uses each side's real, un-normalized spelling.
//
// Returns { wordSegments, extraSegments }, each an array of { text, kind }
// in reading order:
//   - wordSegments are "match" (correct as typed), "sub" (wrong letter
//     where a right one was expected -- shown as the correct letter), or
//     "missing" (a correct letter the user never typed). Concatenating
//     wordSegments' text in order always renders the correct answer's own
//     spelling, intact -- these are the only segments a caller should
//     render as part of "the correct answer".
//   - extraSegments are "extra": a letter the user typed that isn't in the
//     correct answer at all, shown as what was actually typed. These are
//     kept OUT of wordSegments and returned separately on purpose --
//     rendering an "extra" segment directly after correct-answer text
//     (e.g. "tandhur" immediately followed by a struck-through "a") reads
//     as if the correct answer itself contains the struck-through mistake,
//     which is exactly the confusing case this split exists to prevent.
//     Callers should render wordSegments as one clean, uninterrupted word
//     and, if extraSegments is non-empty, show it as a clearly separate
//     annotation instead of splicing it into the word.
function diffAnswer(rawInput, correctAnswer) {
  const inputTraced = normalizeWithTrace(rawInput);
  const correctTraced = normalizeWithTrace(correctAnswer);
  const ops = levenshteinAlign(inputTraced.normalized, correctTraced.normalized);

  const segments = ops.map((step) => {
    if (step.op === "match" || step.op === "sub") {
      const [s, e] = correctTraced.spans[step.bIndex];
      return { text: correctAnswer.slice(s, e), kind: step.op === "match" ? "match" : "sub" };
    }
    if (step.op === "ins") {
      const [s, e] = correctTraced.spans[step.bIndex];
      return { text: correctAnswer.slice(s, e), kind: "missing" };
    }
    // "del": present in what was typed, absent from the correct answer.
    const [s, e] = inputTraced.spans[step.aIndex];
    return { text: rawInput.slice(s, e), kind: "extra" };
  });

  // Merge adjacent same-kind segments so a run of matching letters renders
  // as one span instead of one per character.
  const merged = [];
  for (const seg of segments) {
    const last = merged[merged.length - 1];
    if (last && last.kind === seg.kind) {
      last.text += seg.text;
    } else {
      merged.push({ text: seg.text, kind: seg.kind });
    }
  }

  return {
    wordSegments: merged.filter((seg) => seg.kind !== "extra"),
    extraSegments: merged.filter((seg) => seg.kind === "extra"),
  };
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    normalizeAnswer,
    generateAcceptedAnswers,
    isAnswerCorrect,
    isCorrectForItem,
    normalizeWithTrace,
    levenshteinAlign,
    closestAcceptedAnswer,
    diffAnswer,
  };
}
